人员管理系统/urls.py
from django.contrib import admin
from django.urls import path, re_path
from UMS.views import depart, num, user, admin, account,order, chart, file
urlpatterns = [
    #path('admin/', admin.site.urls),

    # 部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    path('depart/<int:nid>/edit/', depart.depart_edit),
    path('depart/multi/', depart.depart_multi),

    #用户管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),

    #靓号管理
    path('num/list/', num.num_list),
    path('num/add/', num.num_add),
    path('num/<int:nid>/edit/', num.num_edit),
    path('num/<int:nid>/delete/', num.num_delete),

    #管理员
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),

    #登录
    path('login/', account.account_login),
    path('logout/', account.account_logout),

    #订单
    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/delete/', order.order_delete),
    path('order/detail/', order.order_detail),
    path('order/edit/', order.order_edit),

    #数据统计
    path('chart/list/', chart.chart_list),

    #数据上传
    path('file/upload/', file.file_upload),

]

UMS/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name="标题", max_length=32)
    def __str__(self):
        return self.title

class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    # create_time = models.DateTimeField(verbose_name="创建时间")
    create_time = models.DateField(verbose_name="创建时间")
    #构建外键, 可以为空时null=True, blank=True
    depart = models.ForeignKey(verbose_name="所属部门", to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL)
    gender_choices=(
        (1,"男"),
        (2,"女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)

class PrettyNum(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name="电话号码", max_length=11)
    price = models.IntegerField(verbose_name="价格")
    level_choices=(
        (1, "超级靓"),
        (2, "特别靓"),
        (3, "一般靓"),
    )
    level = models.SmallIntegerField(verbose_name="靓号等级", choices=level_choices, default=1)
    status_choices=(
        (1, "未占用"),
        (2, "已占用"),
    )
    status = models.SmallIntegerField(verbose_name="占用状态", choices=status_choices, default=1)

class Admin(models.Model):
    """员工表"""
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    def __str__(self):
        return self.username

class Order(models.Model):
    """订单"""
    oid = models.CharField(verbose_name="订单号", max_length=32)
    title = models.CharField(verbose_name="商品名称", max_length=32)
    price = models.IntegerField(verbose_name="价格")
    status_choice = (
        (1, "待支付"),
        (2, "已支付"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choice, default=1)
    admin = models.ForeignKey(verbose_name="负责人", to="Admin", on_delete=models.CASCADE)

UMS/views/account.py
from django import forms
from django.shortcuts import render, redirect, HttpResponse
from UMS import models
from UMS.utils.encrypt import md5


class AdminForm(forms.Form):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(
            attrs={"class": "form-control",
                   "placeholder": "用户名",
                   }
        ),
        required= True,
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(
            attrs={"class": "form-control",
                   "placeholder": "密码",
                   },
            render_value= True,
        ),
        required=True,
    )
    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)


def account_login(request):
    if request.method == "GET":
        form = AdminForm()
        return render(request, 'account_login.html', {"form": form})
    form = AdminForm(data=request.POST)
    if form.is_valid():
        admin_obj = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_obj:
            form.add_error("password", "用户或密码错误")
            return render(request, 'account_login.html', {"form": form})
        request.session['info'] = {"id": admin_obj.id, "username": admin_obj.username}
        return redirect('/admin/list/')
    return render(request, 'account_login.html', {"form": form})


def account_logout(request):
    request.session.clear()
    return redirect('/login/')

UMS/views/admin.py
from django.shortcuts import render,redirect
from UMS import models
from UMS.utils.pagination import Pagination

def admin_list(request):
    date_dict = {}
    search_data = request.GET.get("q", "")
    if search_data:
        date_dict["mobile__contains"] = search_data
    queryset = models.Admin.objects.filter(**date_dict)

    page_obj = Pagination(request, queryset)

    context = {
        "search_data": search_data,
        "queryset": page_obj.page_queryset,
        "page_string": page_obj.html(),
    }
    return render(request, "admin_list.html", context)
from django import forms
from UMS.utils.form import AdminModelForm

def admin_add(request):
    if request.method == "GET":
        form = AdminModelForm()
    else:
        form = AdminModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/admin/list/')
    context = {
        "title": "新建管理员",
        "form": form,
    }
    return render(request, "exchange.html", context)


def admin_edit(request, nid):

    row_obj = models.Admin.objects.filter(id=nid).first()
    if not row_obj:
        return redirect('/admin/list/')
    if request.method == "GET":
        form = AdminModelForm(instance=row_obj)
    else:
        form = AdminModelForm(data=request.POST, instance=row_obj)
        if form.is_valid():
            form.save()
            return redirect('/admin/list/')
    context = {
        "title": "管理员编辑",
        "form": form,
    }
    return render(request, 'exchange.html', context)

def admin_delete(request, nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list/')

UMS/views/chart.py
from django.shortcuts import render,redirect

def chart_list(request):
    return render(request, "chart_list.html")

UMS/views/depart.py
from django.shortcuts import render, redirect
from UMS.models import Department


def depart_list(request):
    """部门列表"""
    de_list = Department.objects.all()
    return render(request, "depart_list.html", {"de_list":de_list})

def depart_add(request):
    """添加部门"""
    if request.method == "POST":
        title = request.POST.get("title")
        Department.objects.create(title=title)
        return redirect("/depart/list/")
    return render(request, "depart_add.html")

def depart_delete(request):
    nid=request.GET.get("nid")
    Department.objects.filter(id=nid).delete()
    return redirect("/depart/list/")

def depart_edit(request,nid):
    if request.method == "GET":
        e_depart = Department.objects.filter(id=nid).first()
        return render(request, "depart_edit.html", {"e_depart":e_depart})
    e_depart = request.POST.get("title")
    Department.objects.filter(id=nid).update(title=e_depart)
    return redirect("/depart/list/")

from openpyxl import load_workbook
def depart_multi(request):
    file_object = request.FILES.get("exc")
    wb = load_workbook(file_object)
    sheet = wb.worksheets[0]

UMS/views/file.py
from django.shortcuts import render, redirect, HttpResponse


def file_upload(request):
    if request.method == "GET":
        return render(request, 'file_upload.html')
    file_object = request.FILES.get("avatar")

    f = open(file_object.name, mode="wb")
    for chunk in file_object.chunks():
        f.write(chunk)
    f.close()
    return HttpResponse("上传成功")

UMS/views/num.py
from django.shortcuts import render, redirect
from UMS.utils.pagination import Pagination
from UMS.utils.form import NumModelform
from UMS import models

def num_list(request):

    #搜索框
    date_dict = {}
    search_data = request.GET.get("q","")
    if search_data:
        date_dict["mobile__contains"] = search_data
    queryset = models.PrettyNum.objects.filter(**date_dict).order_by("level")


    page_obj = Pagination(request, queryset)

    context={
        "search_data": search_data,
        "queryset": page_obj.page_queryset,
        "page_string": page_obj.html(),
    }
    return render(request, "prettynum_list.html", context)

def num_add(request):
    if request.method == "GET":
        form = NumModelform()
        context ={
            "form": form
        }
        return render(request, "prettynum_add.html", context)
    form = NumModelform(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/num/list/')
    return render(request, "prettynum_add.html", {"form":form})

def num_edit(request, nid):
    row_object = models.PrettyNum.objects.filter(id=nid).first()
    if request.method == "GET":
        form = NumModelform(instance=row_object)
        return render(request, 'prettynum_edit.html', {"form":form})
    form = NumModelform(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/num/list/')
    return render(request, 'prettynum_edit.html', {"form":form})

def num_delete(request, nid):
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect('/num/list/')

UMS/views/order.py
from django.shortcuts import render, redirect
from UMS.utils.form import OrderModelform
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import random
from datetime import datetime
from UMS.models import Order
from UMS.utils.pagination import Pagination


def order_list(request):
    queryset = Order.objects.all().order_by("-id")
    page_obj = Pagination(request, queryset)
    form = OrderModelform()
    context = {
        "form": form,
        "queryset": page_obj.page_queryset,
        "page_string": page_obj.html(),
    }
    return render(request, "order_list.html", context)


@csrf_exempt
def order_add(request):
    """新建订单"""
    form = OrderModelform(data=request.POST)
    if form.is_valid():
        form.instance.oid = datetime.now().strftime("%Y%m%d%H%M%S") + str(random.randint(1000, 9999))
        form.instance.admin_id = request.session["info"]["id"]
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})


def order_delete(request):
    uid = request.GET.get("uid")
    exist = Order.objects.filter(id=uid).exists()
    if not exist:
        return JsonResponse({"status": False, "error": "要删除的数据不存在，删除失败"})
    Order.objects.filter(id=uid).delete()
    return JsonResponse({"status": True})


def order_detail(request):
    uid = request.GET.get("uid")
    row_dict = Order.objects.filter(id=uid).values("title", "price", "status").first()
    if not row_dict:
        return JsonResponse({"status": False, "error": "编辑内容不存在，请刷新后重新编辑。"})
    result = {
        "status": True,
        "data": row_dict,
    }
    return JsonResponse(result)



@csrf_exempt
def order_edit(request):
    uid = request.GET.get("uid")
    row_obj = Order.objects.filter(id=uid).first()
    if not row_obj:
        return JsonResponse({"status": False, "tip": "编辑数据不存在"})
    form = OrderModelform(data=request.POST, instance=row_obj)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})

UMS/views/user.py
from django.shortcuts import render, redirect
from UMS.models import UserInfo
from UMS.utils.pagination import Pagination
from UMS.utils.form import UserModelform

def user_list(request):
    u_list = UserInfo.objects.all()
    user_page_obj = Pagination(request, u_list)
    context={
        "u_list": user_page_obj.page_queryset,
        "page_string": user_page_obj.html()
    }

    return render(request, 'user_list.html', context)

def user_add(request):
    if request.method == "GET":
        form = UserModelform()
        context ={
            "form": form
        }
        return render(request, "user_add.html", context)
    form = UserModelform(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/user/list/')
    return render(request, "user_add.html", {"form":form})

def user_edit(request, nid):
    row_object = UserInfo.objects.filter(id=nid).first()
    if request.method == "GET":
        form = UserModelform(instance=row_object)
        context ={
            "form": form
        }
        return render(request, "user_add.html", context)
    form = UserModelform(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/user/list/')
    return render(request, "user_edit.html", {"form":form})

def user_delete(request, nid):
    UserInfo.objects.filter(id=nid).delete()
    return redirect("/user/list/")

UMS/templates/account_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>账号登录</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 500px;
            height: 400px;
            border: 1.5px solid #8c8c8c;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;

            padding-left: 50px;
            padding-right: 50px;
            padding-top: 40px;
        }
        .account h2{
            text-align: center;
            margin-bottom: 20px;
        }
        .btn{
            margin-left: auto;
            margin-right: auto;
        }
        .login{
            margin-top: 20px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>账号登录</h2>
    <form method="post" novalidate>
    {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label>{{ field.label }}</label>
            {{ field }}
            <span style="color:red;">{{ field.errors.0 }}</span>
        </div>
        {% endfor %}
        <div class="form-group">
                        <label for="id_code">图片验证码</label>
                        <div class="row">
                            <div class="col-xs-7">
                                <input type="text" name="code" class="form-control" placeholder="请输入图片验证码" required="" id="id_code">
                                <span style="color: red;"></span>
                            </div>
                            <div class="col-xs-5">
                                <img id="image_code" src="/image/code/">
                            </div>
                        </div>
                    </div>
        <div class="login">
            <button type="submit" class="btn btn-primary">登   录</button>
        </div>

    </form>

</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

UMS/templates/file_upload.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="avatar">
            <button type="submit" class="btn-primary">提交</button>
        </form>
    </div>


{% endblock %}

UMS/templates/order_list.html
{% extends 'layout.html' %}

{% block content %}
    <!-- Button trigger modal -->
    <button id="btnAdd" type="button" class="btn btn-primary" style="margin-bottom: 5px">
        新建订单
    </button>

    <!-- 新建订单Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建订单</h4>
                </div>
                <div class="modal-body">
                    <form id="formAdd">
                        <div class="clearfix">
                            {% for field in form %}
                                <div class="col-xs-6">
                                    <div class="form-group" style="position:relative; margin-bottom: 20px">
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        <span class="error-msg" style="color: #af2121; position: absolute"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                </div>
            </div>
        </div>
    </div>

    <!-- 订单列表 -->
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 订单信息
        </div>

        <!-- Table -->
        <table class="table table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>订单号</th>
                <th>商品名称</th>
                <th>价格</th>
                <th>支付状态</th>
                <th>管理员</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.oid }}</td>
                    <td>{{ obj.title }}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>{{ obj.admin.username }}</td>
                    <td>
                        <input uid="{{ obj.id }}" type="button" class="btn-primary btn-xs btn-edit" value="编辑">
                        <input uid="{{ obj.id }}" type="button" class="btn-danger btn-xs btn-delete" value="删除">
                        <!-- 删除订单Modal -->
                        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
                             aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                                    <h4>是否确认删除</h4>
                                    <p>删除后相关数据将彻底清除</p>
                                    <p style="text-align: right">
                                        <button id="confirmdelete" type="button" class="btn btn-danger">删除</button>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                                    </p>
                                </div>

                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- 分页插件 -->
    <ul class="pagination">
        {{ page_string }}
    </ul>

{% endblock %}

{% block js %}
    <script type="text/javascript">
        var DELETE_ID;
        var EDIT_ID;
        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();
        })

        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {
                EDIT_ID = undefined;
                //清空表单数据
                $("#formAdd")[0].reset();
                //表头赋值
                $("#myModalLabel").text("新建订单");
                //弹出模块
                $('#myModal').modal('show');
            })
        }

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                $(".error-msg").text("");
                if (EDIT_ID) {
                    doEdit();
                } else {
                    doAdd();
                }
            })
        }

        function doAdd() {
            $.ajax({
                url: "/order/add/",
                type: "post",
                data: $("#formAdd").serialize(),
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        alert("创建成功");
                        //表单置空
                        $("#formAdd")[0].reset();
                        //弹窗隐藏
                        $('#myModal').modal('hide');
                        //页面刷新
                        location.reload()
                    } else {
                        $.each(res.error, function (name, errorList) {
                            $("#id_" + name).next().text(errorList[0]);
                        })
                    }

                }
            })
        }

        function doEdit() {
            $.ajax({
                url: "/order/edit/" + "?uid=" + EDIT_ID,
                type: "post",
                data: $("#formAdd").serialize(),
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        alert("修改成功");
                        //表单置空
                        $("#formAdd")[0].reset();
                        //弹窗隐藏
                        $('#myModal').modal('hide');
                        //页面刷新
                        location.reload();
                    } else {
                        if (res.tip) {
                            alert(res.tip);
                        } else {
                            $.each(res.error, function (name, errorList) {
                                $("#id_" + name).next().text(errorList[0]);
                            })
                        }
                    }
                }
            })
        }

        function bindBtnDeleteEvent() {
            $(".btn-delete").click(function () {
                $("#deleteModal").modal('show');
                DELETE_ID = $(this).attr("uid");

            })
        }

        function bindBtnConfirmDeleteEvent() {
            $("#confirmdelete").click(function () {
                $.ajax({
                    url: "/order/delete/",
                    type: "get",
                    data: {
                        uid: DELETE_ID
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            $('#deleteModal').modal('hide');
                            location.reload();
                        } else {
                            alert(res.error());
                        }
                    }

                })
            })
        }

        function bindBtnEditEvent() {
            $(".btn-edit").click(function () {
                $("#formAdd")[0].reset();
                EDIT_ID = $(this).attr("uid");
                $.ajax({
                    url: "/order/detail/",
                    type: "get",
                    data: {
                        uid: EDIT_ID
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            $.each(res.data, function (name, value) {
                                $("#id_" + name).val(value);
                            });
                            //修改标题
                            $("#myModalLabel").text("编辑订单");
                            //显示框
                            $('#myModal').modal('show');
                        } else {
                            alert(res.error)
                        }
                    }
                })

            })
        }
    </script>
{% endblock %}

UMS/templates/prettynum_list.html
{% extends 'layout.html' %}
{% block content %}
    {#    <div style="margin-bottom: 3px">#}
    {#        <a type="button" class="btn btn-success btn-sm" href="/num/add/">#}
    {#            添加信息#}
    {#        </a>#}
    {#        <div class="input-group">#}
    {#            <input type="text" class="form-control" placeholder="电话号码">#}
    {#            <span class="input-group-btn">#}
    {#                <button class="btn btn-default" type="button">搜索</button>#}
    {#            </span>#}
    {#        </div>#}
    {#    </div>#}
    <div class="row" style="margin-bottom: 2px">
        <div class="col-lg-6">
            <a type="button" style="float:left; width: 100px" class="btn btn-success" href="/num/add/">
                添加信息
            </a>
        </div><!-- /.col-lg-6 -->
        <div class="col-lg-6">
            <form method="get">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" value="{{ search_data }}" placeholder="电话号码"
                           style="float:right; width: 300px">
                    <span class="input-group-btn">
                <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"
                                                                    aria-hidden="true"></span></button>
              </span>
                </div><!-- /input-group -->

            </form>
        </div><!-- /.col-lg-6 -->
    </div><!-- /.row -->


    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 靓号信息
        </div>

        <!-- Table -->
        <table class="table table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>号码</th>
                <th>价格</th>
                <th>等级</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.mobile }}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.get_level_display }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/num/{{ obj.id }}/edit/">编辑</a>
                        <a class="btn btn-danger btn-xs" href="/num/{{ obj.id }}/delete/">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <nav aria-label="...">
        <ul class="pagination">
            {{ page_string }}
        </ul>
    </nav>
{% endblock %}

UMS/templates/user_add.html
{% extends 'layout.html' %}
{% load static %}
{% block css %}

    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css' %}">

{% endblock %}

{% block content %}
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">添加用户</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="inputdepart" class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">
                            {{ field }}
                            <span style="color:red;">{{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datetimepicker-master/js/locales/bootstrap-datetimepicker.zh-CN.js' %}">
    </script>
    <script>
        $(function (){
            $('#id_create_time').datetimepicker({
            language: 'zh-CN', // 中文语言包
            autoclose: 1, // 选中日期后自动关闭
            format: 'yyyy-mm-dd', // 日期格式
            minView: "month", // 最小日期显示单元，这里最小显示月份界面，即可以选择到日
            todayBtn: 1, // 显示今天按钮
            todayHighlight: 1, // 显示今天高亮
            });
        })
    </script>
{% endblock %}

UMS/templates/user_list.html
{% extends 'layout.html' %}
{% block content %}
    <div style="margin-bottom: 3px">
        <a type="button" class="btn btn-success btn-sm" href="/user/add/">
            添加信息
        </a>
    </div>
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
          <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>  人员信息
      </div>

      <!-- Table -->
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>密码</th>
            <th>年龄</th>
            <th>账户余额</th>
            <th>创建时间</th>
            <th>性别</th>
            <th>所属部门</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        {% for obj in u_list %}
          <tr>
            <td>{{ obj.id }}</td>
            <td>{{ obj.name }}</td>
            <td>{{ obj.password }}</td>
            <td>{{ obj.age }}</td>
            <td>{{ obj.account }}</td>
            <td>{{ obj.create_time|date:"Y-m-d" }}</td>
            <td>{{ obj.get_gender_display }}</td>
            <td>{{ obj.depart.title }}</td>
            <td>
                <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <ul class="pagination">
        {{ page_string }}
    </ul>
{% endblock %}